
INCLUDE(${CMakeModules}/Cadkit.cmake)

# Remove d postfix for plugins
IF (CMAKE_BUILD_TYPE STREQUAL "Debug")
SET(CMAKE_DEBUG_POSTFIX )
ENDIF (CMAKE_BUILD_TYPE STREQUAL "Debug")

# ---- Change the Suffix on the Generated library --------------------------------
MACRO(CADKIT_PLUGIN PLUGIN_NAME)
	#SET_TARGET_PROPERTIES (${PLUGIN_NAME} PROPERTIES SUFFIX ".plug" )
	#SET_TARGET_PROPERTIES (${PLUGIN_NAME} PROPERTIES PREFIX "" )
	##SET_TARGET_PROPERTIES (${PLUGIN_NAME} PROPERTIES DEBUG_SUFFIX ".plugd" )
	
	IF (CMAKE_BUILD_TYPE STREQUAL "Debug")
		SET_TARGET_PROPERTIES (${PLUGIN_NAME} PROPERTIES PREFIX "" SUFFIX ".plugd" )
	ELSE (CMAKE_BUILD_TYPE STREQUAL "Debug")
		SET_TARGET_PROPERTIES (${PLUGIN_NAME} PROPERTIES PREFIX "" SUFFIX ".plug" )
	ENDIF (CMAKE_BUILD_TYPE STREQUAL "Debug")
	
	INSTALL(TARGETS ${PLUGIN_NAME}
			RUNTIME DESTINATION bin
			LIBRARY DESTINATION bin
			ARCHIVE DESTINATION bin )
			
	# Add the target label.
	SET_TARGET_PROPERTIES(${PLUGIN_NAME} PROPERTIES PROJECT_LABEL "Plugin ${PLUGIN_NAME}")

ENDMACRO(CADKIT_PLUGIN PLUGIN_NAME)
