
SET(VR_JUGGLER_VERSION 2.0 CACHE STRING "Enter VR Juggler Version (2.0 or 2.2).")

IF(VR_JUGGLER_VERSION MATCHES 2.0)
  INCLUDE( FindVRJuggler20 )
ENDIF(VR_JUGGLER_VERSION MATCHES 2.0)

IF(VR_JUGGLER_VERSION MATCHES 2.2)
  INCLUDE( FindVRJuggler22 )
ENDIF(VR_JUGGLER_VERSION MATCHES 2.2)
