
FIND_PATH(CURL_INCLUDE_DIR curl/curl.h "$ENV{CURL_INC_DIR}" )

# Look for the library.
FIND_LIBRARY(CURL_LIBRARY NAMES curl "$ENV{CURL_LIB_DIR}" )
	
MARK_AS_ADVANCED(CURL_INCLUDE_DIR)
MARK_AS_ADVANCED(CURL_LIBRARY)
