
# Include all variables, flags, etc...
include Make/header.mak

# C++ source files.
CPP_FILES = \
./File/Remove.cpp \
./File/Temp.cpp \
./File/Make.cpp \
./State/Busy.cpp \
./Predicates/CanWrite.cpp \
./CommandLine/Arguments.cpp \
./CommandLine/Options.cpp \
./CommandLine/Flags.cpp \
./Trace/Scope.cpp \
./Trace/Print.cpp \
./Documents/Document.cpp \
./Documents/Manager.cpp \
./Types/Types.cpp \
./Functions/Color.cpp \
./Functions/Guid.cpp \
./Scope/Timer.cpp \
./Base/InstanceManager.cpp \
./Base/Referenced.cpp \
./Base/Typed.cpp \
./Resources/CancelButton.cpp \
./Resources/EventQueue.cpp \
./Resources/ReportErrors.cpp \
./Resources/StatusBar.cpp \
./Resources/MenuBar.cpp \
./Resources/ProgressBar.cpp \
./Resources/TextWindow.cpp \
./DLL/Library.cpp \
./DLL/Listener.cpp \
./DLL/Loader.cpp \
./Errors/Stack.cpp \
./Errors/Error.cpp \
./User/Directory.cpp \
./App/Controller.cpp \
./Devices/State.cpp \
./Devices/Factory.cpp \
./Devices/BaseDevice.cpp \
./System/Environment.cpp \
./System/Directory.cpp \
./System/Memory.cpp \
./System/Sleep.cpp \
./System/LastError.cpp \
./System/Host.cpp \
./System/Screen.cpp \
./System/Socket.cpp \
./System/Clock.cpp \
./System/DateTime.cpp \
./Components/Object.cpp \
./Components/Registry.cpp \
./Components/Manager.cpp \
./Threads/Task.cpp \
./Threads/Mutex.cpp \
./Threads/Thread.cpp \
./Threads/Pool.cpp \
./Threads/Manager.cpp \
./Threads/RecursiveMutex.cpp \
./Threads/Callback.cpp \
./ID/GUID.cpp \
./Shared/Preferences.cpp

LOCAL_INCLUDE = \
	-I../

# The name of the thing we are making.
TARGET = Usul

# Include the rules for make...
include Make/library.mak
