SHELL = /bin/sh

# Must be defined before Makedefs is included.
PKG_NAME = Usul
COMPILE_GUARD = USUL

# Include all variables, flags, etc...
include Make/Makedefs

INCLUDES = \
	-I../

LIBS = 

LIB_DIRS = 

# Include the rules for make...
include Make/Makerules
