/////////////////////////////////////////////////////////////////////////////
// Name:        MaterialEditor.cpp
// Purpose:     
// Author:      Perry Miller
// Modified by: 
// Created:     12/07/05 11:44:08
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 12/07/05 11:44:08

#if defined(__GNUG__) && !defined(__APPLE__)
#pragma implementation "MaterialEditor.h"
#endif

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
#pragma hdrstop
#endif

#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif

////@begin includes
////@end includes

#include "MaterialEditor.h"

////@begin XPM images
////@end XPM images

/*!
 * MaterialEditor type definition
 */

IMPLEMENT_CLASS( MaterialEditor, wxFrame )

/*!
 * MaterialEditor event table definition
 */

BEGIN_EVENT_TABLE( MaterialEditor, wxFrame )

////@begin MaterialEditor event table entries
////@end MaterialEditor event table entries

END_EVENT_TABLE()

/*!
 * MaterialEditor constructors
 */

MaterialEditor::MaterialEditor( )
{
}

MaterialEditor::MaterialEditor( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
    Create( parent, id, caption, pos, size, style );
}

/*!
 * MaterialEditor creator
 */

bool MaterialEditor::Create( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
////@begin MaterialEditor member initialisation
////@end MaterialEditor member initialisation

////@begin MaterialEditor creation
    SetParent(parent);
    CreateControls();
    Centre();
////@end MaterialEditor creation
    return true;
}

/*!
 * Control creation for MaterialEditor
 */

void MaterialEditor::CreateControls()
{    
////@begin MaterialEditor content construction
    // Generated by DialogBlocks, 12/08/05 16:27:52 (unregistered)

    wxXmlResource::Get()->LoadFrame(this, GetParent(), wxT("ID_FRAME"));
////@end MaterialEditor content construction

    // Create custom windows not generated automatically here.

////@begin MaterialEditor content initialisation

////@end MaterialEditor content initialisation
}

/*!
 * Should we show tooltips?
 */

bool MaterialEditor::ShowToolTips()
{
    return true;
}

/*!
 * Get bitmap resources
 */

wxBitmap MaterialEditor::GetBitmapResource( const wxString& name )
{
    // Bitmap retrieval
////@begin MaterialEditor bitmap retrieval
    wxUnusedVar(name);
    return wxNullBitmap;
////@end MaterialEditor bitmap retrieval
}

/*!
 * Get icon resources
 */

wxIcon MaterialEditor::GetIconResource( const wxString& name )
{
    // Icon retrieval
////@begin MaterialEditor icon retrieval
    wxUnusedVar(name);
    return wxNullIcon;
////@end MaterialEditor icon retrieval
}
