
FIND_PATH(CURL_INCLUDE_DIR curl/curl.h "$ENV{CURL_INC_DIR}" )

# Look for the library.
FIND_LIBRARY(CURL_LIBRARY_RELEASE NAMES curl  "$ENV{CURL_LIB_DIR}" )
FIND_LIBRARY(CURL_LIBRARY_DEBUG   NAMES curld "$ENV{CURL_LIB_DIR}" )

CADKIT_SET_DEBUG_RELEASE_LIBRARY( CURL_LIBRARY CURL_LIBRARY_DEBUG CURL_LIBRARY_RELEASE )
	
MARK_AS_ADVANCED(CURL_INCLUDE_DIR)
MARK_AS_ADVANCED(CURL_LIBRARY)
