/////////////////////////////////////////////////////////////////////////////
// Name:        LeftPanel.h
// Purpose:     
// Author:      Perry Miller
// Modified by: 
// Created:     12/16/05 23:33:29
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 12/16/05 23:33:29

#ifndef _LEFT_PANEL_H_
#define _LEFT_PANEL_H_

#if defined(__GNUG__) && !defined(__APPLE__)
#pragma interface "LeftPanel.cpp"
#endif

/*!
 * Includes
 */

////@begin includes
#include "wx/xrc/xmlres.h"
#include "wx/notebook.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_LEFT_PANEL 10000
#define SYMBOL_LEFTPANEL_STYLE 0
#define SYMBOL_LEFTPANEL_TITLE _("LeftPanel")
#define SYMBOL_LEFTPANEL_IDNAME ID_LEFT_PANEL
#define SYMBOL_LEFTPANEL_SIZE wxSize(400, 300)
#define SYMBOL_LEFTPANEL_POSITION wxDefaultPosition
////@end control identifiers

/*!
 * Compatibility
 */

#ifndef wxCLOSE_BOX
#define wxCLOSE_BOX 0x1000
#endif

/*!
 * LeftPanel class declaration
 */

class LeftPanel: public wxPanel
{    
    DECLARE_DYNAMIC_CLASS( LeftPanel )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    LeftPanel( );
    LeftPanel( wxWindow* parent, wxWindowID id = SYMBOL_LEFT_PANEL_IDNAME, const wxPoint& pos = SYMBOL_LEFT_PANEL_POSITION, const wxSize& size = SYMBOL_LEFT_PANEL_SIZE, long style = SYMBOL_LEFT_PANEL_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_LEFT_PANEL_IDNAME, const wxPoint& pos = SYMBOL_LEFT_PANEL_POSITION, const wxSize& size = SYMBOL_LEFT_PANEL_SIZE, long style = SYMBOL_LEFT_PANEL_STYLE );

    /// Creates the controls and sizers
    void CreateControls();

////@begin LeftPanel event handler declarations

////@end LeftPanel event handler declarations

////@begin LeftPanel member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end LeftPanel member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin LeftPanel member variables
////@end LeftPanel member variables
};

#endif
    // _LEFT_PANEL_H_
