/////////////////////////////////////////////////////////////////////////////
// Name:        MaterialEditor.h
// Purpose:     
// Author:      Perry Miller
// Modified by: 
// Created:     12/07/05 11:44:08
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 12/07/05 11:44:08

#ifndef _MATERIALEDITOR_H_
#define _MATERIALEDITOR_H_

#if defined(__GNUG__) && !defined(__APPLE__)
#pragma interface "MaterialEditor.cpp"
#endif

/*!
 * Includes
 */

////@begin includes
#include "wx/xrc/xmlres.h"
#include "wx/frame.h"
#include "wx/datectrl.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_FRAME 10000
#define SYMBOL_MATERIALEDITOR_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX
#define SYMBOL_MATERIALEDITOR_TITLE _("MaterialEditor")
#define SYMBOL_MATERIALEDITOR_IDNAME ID_FRAME
#define SYMBOL_MATERIALEDITOR_SIZE wxSize(600, 300)
#define SYMBOL_MATERIALEDITOR_POSITION wxDefaultPosition
////@end control identifiers

/*!
 * Compatibility
 */

#ifndef wxCLOSE_BOX
#define wxCLOSE_BOX 0x1000
#endif

/*!
 * MaterialEditor class declaration
 */

class MaterialEditor: public wxFrame
{    
    DECLARE_CLASS( MaterialEditor )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    MaterialEditor( );
    MaterialEditor( wxWindow* parent, wxWindowID id = SYMBOL_MATERIALEDITOR_IDNAME, const wxString& caption = SYMBOL_MATERIALEDITOR_TITLE, const wxPoint& pos = SYMBOL_MATERIALEDITOR_POSITION, const wxSize& size = SYMBOL_MATERIALEDITOR_SIZE, long style = SYMBOL_MATERIALEDITOR_STYLE );

    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_MATERIALEDITOR_IDNAME, const wxString& caption = SYMBOL_MATERIALEDITOR_TITLE, const wxPoint& pos = SYMBOL_MATERIALEDITOR_POSITION, const wxSize& size = SYMBOL_MATERIALEDITOR_SIZE, long style = SYMBOL_MATERIALEDITOR_STYLE );

    /// Creates the controls and sizers
    void CreateControls();

////@begin MaterialEditor event handler declarations

////@end MaterialEditor event handler declarations

////@begin MaterialEditor member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end MaterialEditor member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin MaterialEditor member variables
////@end MaterialEditor member variables
};

#endif
    // _MATERIALEDITOR_H_
