# Include the header to set up the environment.
include $(GSG_ROOT_DIR)/Make/header.mak

# C++ source files.
CPP_FILES = \
	GlContext.cpp \
	GlDraw.cpp \
	OglDll.cpp

# The include path.
LOCAL_INCLUDE =

# The libraries to link to.
LOCAL_LIBS = 

# Any flags for the compiler.
LOCAL_CPP_FLAGS = -DCOMPILING_GSG_OPENGL

# The name of the thing we are making.
TARGET = gsg_opengl

# The common rules for compiling are in here.
include $(GSG_ROOT_DIR)/Make/library.mak
