# Include the header to set up the environment.
include $(CADKIT_ROOT_DIR)/Make/header.mak

# C++ source files.
CPP_FILES = MatrixNN.cpp

# The include path.
LOCAL_INCLUDE =

# The libraries to link to.
LOCAL_LIBS = -lm

# Any flags for the compiler. 
LOCAL_CPP_FLAGS =

# Any flags for the linker.
LOCAL_LINK_FLAGS =

# The name of the thing we are making.
TARGET = matrixNN

# The common rules for compiling are in here.
include $(CADKIT_ROOT_DIR)/Make/executable.mak
