
INCLUDE ( Cadkit )

# Remove d postfix for plugins
#IF (CMAKE_BUILD_TYPE STREQUAL "Debug")
#SET(CMAKE_DEBUG_POSTFIX )
#ENDIF (CMAKE_BUILD_TYPE STREQUAL "Debug")

# ---- Change the Suffix on the Generated library --------------------------------
# Deprecated.  Use CADKIT_ADD_PLUGIN instead.
MACRO(CADKIT_PLUGIN PLUGIN_NAME)

	SET_TARGET_PROPERTIES(${TARGET_NAME} PROPERTIES DEBUG_POSTFIX "d")
	SET_TARGET_PROPERTIES (${PLUGIN_NAME} PROPERTIES PREFIX "" SUFFIX ".plug" )

	#IF (CMAKE_BUILD_TYPE STREQUAL "Debug")
	#	SET_TARGET_PROPERTIES (${PLUGIN_NAME} PROPERTIES PREFIX "" SUFFIX ".plugd" )
	#ELSE (CMAKE_BUILD_TYPE STREQUAL "Debug")
	#	SET_TARGET_PROPERTIES (${PLUGIN_NAME} PROPERTIES PREFIX "" SUFFIX ".plug" )
	#ENDIF (CMAKE_BUILD_TYPE STREQUAL "Debug")
	
	INSTALL(TARGETS ${PLUGIN_NAME}
			RUNTIME DESTINATION bin
			LIBRARY DESTINATION bin
			ARCHIVE DESTINATION bin )
			
	# Add the target label.
	SET_TARGET_PROPERTIES(${PLUGIN_NAME} PROPERTIES PROJECT_LABEL "Plugin ${PLUGIN_NAME}")

ENDMACRO(CADKIT_PLUGIN PLUGIN_NAME)


MACRO ( CADKIT_ADD_PLUGIN PLUGIN_NAME )

	# Add the compile guard.
	ADD_DEFINITIONS ("-D${COMPILE_GUARD}")

	# Add the Export.def file.
	IF ( MSVC )
		SET ( SOURCES ${SOURCES} Export.def )
	ENDIF ( MSVC )

	# Create a shared library.
	ADD_LIBRARY( ${PLUGIN_NAME} SHARED ${SOURCES} )

	# Add the debug posfix.
	SET_TARGET_PROPERTIES(${TARGET_NAME} PROPERTIES DEBUG_POSTFIX "d")
	
	# Set the libary prefix and suffix.
	SET_TARGET_PROPERTIES (${PLUGIN_NAME} PROPERTIES PREFIX "" SUFFIX ".plug" )

	# Add the target label.
	IF( MSVC )
		SET ( CADKIT_PLUGIN_LABEL_PREFIX "Plugin:" )
	ELSE( MSVC )
		SET ( CADKIT_PLUGIN_LABEL_PREFIX "Plugin" )
	ENDIF( MSVC )
	
	# Add the target label.
	SET_TARGET_PROPERTIES(${PLUGIN_NAME} PROPERTIES PROJECT_LABEL "${CADKIT_PLUGIN_LABEL_PREFIX} ${PLUGIN_NAME}")
	
	# Link to other Cadkit libraries.
	LINK_CADKIT( ${PLUGIN_NAME} ${CADKIT_LIBRARIES} )
	
	# Link to these other libraries.
	IF ( OTHER_LIBRARIES )
		TARGET_LINK_LIBRARIES( ${PLUGIN_NAME} ${OTHER_LIBRARIES} )
	ENDIF ( OTHER_LIBRARIES )
	
	# Set the install paths.
	INSTALL(TARGETS ${PLUGIN_NAME}
			RUNTIME DESTINATION bin
			LIBRARY DESTINATION bin
			ARCHIVE DESTINATION bin )


ENDMACRO(CADKIT_ADD_PLUGIN PLUGIN_NAME)
