
IF(WIN32)
	FIND_PATH(CURL_INCLUDE_DIR curl/curl.h "$ENV{CURL_INC_DIR}" )
	MARK_AS_ADVANCED(CURL_INCLUDE_DIR)

	# Look for the library.
	FIND_LIBRARY(CURL_LIBRARY NAMES curl "$ENV{CURL_LIB_DIR}" )
	MARK_AS_ADVANCED(CURL_LIBRARY)

	#SET ( CURL_INCLUDE_DIR $ENV{CURL_INC_DIR} )

	#IF (CMAKE_BUILD_TYPE STREQUAL "Debug")
	#	SET ( CURL_LIB curld.lib )
	#ELSE (CMAKE_BUILD_TYPE STREQUAL "Debug")
	#	SET ( CURL_LIB curl.lib )
	#ENDIF (CMAKE_BUILD_TYPE STREQUAL "Debug")

	#SET ( CURL_LIBRARY "$ENV{CURL_LIB_DIR}/${CURL_LIB}" )
	
	MARK_AS_ADVANCED(CURL_INCLUDE_DIR)
	MARK_AS_ADVANCED(CURL_LIBRARY)
	
ELSE(WIN32)
	FIND_PACKAGE(Curl)
ENDIF(WIN32)
