# C++ source files.
CPP_FILES = \
  SlBase.cpp \
  SlPrecompiled.cpp \
  SlPreComputedArrays.cpp \
  SlRefBase.cpp \
  SlTrace.cpp

# The include path.
LOCAL_INCLUDE = 

# The libraries to link to.
LOCAL_LIBS = 

# Any flags for the compiler.
LOCAL_CPP_FLAGS = 

# The name of the thing we are making.
TARGET = CkSl

# The common rules for compiling are in here.
include $(CADKIT_ROOT_DIR)/Make/library.mak
